{% set name = "rsa" %}
{% set version = "4.0" %}
{% set hash_type = "sha256" %}
{% set hash_val = "1a836406405730121ae9823e19c6e806c62bbad73f890574fff50efa4122c487" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  entry_points:
    - pyrsa-priv2pub = rsa.util:private_to_public
    - pyrsa-keygen = rsa.cli:keygen
    - pyrsa-encrypt = rsa.cli:encrypt
    - pyrsa-decrypt = rsa.cli:decrypt
    - pyrsa-sign = rsa.cli:sign
    - pyrsa-verify = rsa.cli:verify
    - pyrsa-encrypt-bigfile = rsa.cli:encrypt_bigfile
    - pyrsa-decrypt-bigfile = rsa.cli:decrypt_bigfile

  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - pyasn1 >=0.1.3

  run:
    - python
    - pyasn1 >=0.1.3

test:
  imports:
    - rsa

  commands:
    - pyrsa-priv2pub --help
    - pyrsa-keygen --help
    - pyrsa-encrypt --help
    - pyrsa-decrypt --help
    - pyrsa-sign --help
    - pyrsa-verify --help
    - pyrsa-encrypt-bigfile --help
    - pyrsa-decrypt-bigfile --help

about:
  home: https://stuvel.eu/rsa
  license: Apache 2.0
  summary: 'Pure-Python RSA implementation'

extra:
  recipe-maintainers:
    - pmlandwehr
